version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      tree-sitter:
        applies-to: version-updates
        patterns:
          - "tree-sitter*"
      minor/patch:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
