[package]
name = "gitu"
version = "0.1.0"
edition = "2021"
#test
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gitu"
path = "src/main.rs"

[[bench]]
name = "show"
harness = false

[dev-dependencies]
pretty_assertions = "1.4.0"
temp-dir = "0.1.12"
criterion = "0.5.1"
pprof = { version = "0.3", features = ["flamegraph"] }

[dependencies]
ansi-to-tui = "3.1.0"
clap = { version = "4.4.16", features = ["derive"] }
crossterm = "0.27.0"
hex = "0.4.3"
insta = "1.34.0"
itertools = "0.12.0"
lazy_static = "1.4.0"
pest = "2.7.6"
pest_derive = "2.7.6"
ratatui = "0.25.0"
strip-ansi-escapes = "0.2.0"
