[package]
name = "gitu"
version = "0.1.0"
edition = "2021"
#test
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
temp-dir = "0.1.12"
pretty_assertions = "1.4.0"

[dependencies]
ansi-to-tui = "3.1.0"
clap = { version = "4.4.16", features = ["derive"] }
crossterm = { version = "0.27.0", features = ["event-stream"] }
ratatui = "0.25.0"
tokio = { version = "1.32.0", features = ["full"] }
tokio-util = "0.7.9"
futures = "0.3.28"
hex = "0.4.3"
insta = "1.34.0"
itertools = "0.12.0"
lazy_static = "1.4.0"
pest = "2.7.6"
pest_derive = "2.7.6"
strip-ansi-escapes = "0.2.0"
