[package]
name = "magitler"
version = "0.1.0"
edition = "2021"
#test
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
hex = "0.4.3"
itertools = "0.12.0"
ratatui = "0.24.0"
regex = "1.10.2"
