[package]
name = "gitu"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bench]]
name = "show"
harness = false

[dev-dependencies]
pretty_assertions = "1.4.0"
temp-dir = "0.1.12"
criterion = "0.5.1"
pprof = { version = "0.13.0", features = ["flamegraph", "criterion"] }

[dependencies]
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive"] }
crossterm = "0.27.0"
git2 = "0.18.2"
insta = "1.35.1"
itertools = "0.12.0"
lazy_static = "1.4.0"
ratatui = "0.26.1"
signal-hook = "0.3.17"
similar = { version = "2.4.0", features = ["unicode"] }
strum = "0.26.1"
