[style]
section_header.fg = "Yellow"
file_header.fg = "Magenta"
hunk_header.fg = "Blue"

line_added.fg = "Green"
line_removed.fg = "Red"

selection_line.mods = "BOLD"
selection_bar.fg = "Blue"
selection_bar.mods= "DIM"
# selection_area.bg = "DarkGray"

hash.fg = "Yellow"
branch.fg = "Green"
remote.fg = "Red"
tag.fg = "Yellow"

command.fg = "Blue"
command.mods = "BOLD"
hotkey.fg = "Magenta"
