[color]
section.fg = "Yellow"
unstaged_file.fg = "Red"
unmerged_file.fg = "Red"
file.fg = "Magenta"
hunk_header.fg = "Blue"
command.fg = "Blue"
command.mods = "BOLD"
hotkey.fg = "Magenta"
branch.fg = "Green"
remote.fg = "Red"
tag.fg = "Yellow"
added.fg = "Green"
removed.fg = "Red"
oid.fg = "Yellow"
cursor_line.mods = "BOLD"
cursor_section.fg = "Blue"
cursor_section.mods = "DIM"
